public class Randomvalus {
    public static int[]generate4DigitRandomValues(int size){ 
        int []randomDigit=new int[size]; 
        for(int i=0;i<5;i++){
            randomDigit[i]=(int)(Math.random()*9000)+1000;

        }
        return randomDigit; 




    }
    public static double[]findAverageMinMax(int[]numbers){
        double []result=new double[3];
        int min_Value=numbers[0];
        int max_Value=numbers[1];
        int sum=0;  
        for(int num:numbers){
            sum+=num;
            min_Value=Math.min(min_Value, num);
            max_Value=Math.max(max_Value,num);

        } 
        double average=(double)sum/numbers.length;
        result[0]=min_Value; 
        result[1]=max_Value; 
        result[2]=average;  
        return result;


    }
    public static void main(String[] args) {
        Randomvalus rv=new Randomvalus(); 
        int []randomDigitResult=generate4DigitRandomValues(5); 
        System.out.println("Random digit generated by array value is "+(randomDigitResult)); 
        double []averageMinMaxresult=findAverageMinMax(randomDigitResult); 
        System.out.println("The minimum value of the number is "+averageMinMaxresult[0]); 
        System.out.println("The maximum value of the number is "+averageMinMaxresult[1]); 
        System.out.println("The average value of the number is "+averageMinMaxresult[2]);



        
    }
    
}